pipeline {
  agent any
  
  
  environment {
    REGISTRY     = "buildserver:5000"
    IMAGE_NAME   = "user-service"
    IMAGE_TAG    = "${BUILD_NUMBER}"
    SCANNER_HOME = tool 'sonar'
  }

  tools {
    nodejs 'node20'
  }

  stages {

    stage('Test') {
      steps {
        dir('node-microservice/app') {
          sh 'npm test'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('node-microservice/app') {
          withSonarQubeEnv('sonar') {
            sh '''
              $SCANNER_HOME/bin/sonar-scanner \
                -Dsonar.projectKey=user-service \
                -Dsonar.projectName=user-service \
                -Dsonar.sources=.
            '''
          }
        }
      }
    }
    
    
    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

   
    stage('Manual Approval') {
      steps {
        emailext(
          subject: "Approval Needed: ${JOB_NAME} #${BUILD_NUMBER}",
          body: """
Hi Team,

Build #${BUILD_NUMBER} is waiting for approval.

Job Name : ${JOB_NAME}
Build URL: ${BUILD_URL}

Please login to Jenkins and approve the build to continue
Docker build & push.
""",
          to: "sudarraja86291@gmail.com"
        )

        input message: "Approve to continue Docker build & push?",
              submitter: "sudarponraja,Sudar,admin",
              ok: "Approve"
      }
    }

    stage('Docker Build') {
      steps {
        dir('node-microservice/app') {
          sh "docker build -t ${IMAGE_NAME} ."
        }
      }
    }

    stage('Docker Tag') {
      steps {
        sh "docker tag ${IMAGE_NAME} ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
      }
    }

    stage('Push to Registry') {
      steps {
        sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
      }
    }
  }


  post {

    success {
      emailext(
        subject: "SUCCESS: ${JOB_NAME} #${BUILD_NUMBER}",
        body: """
Build SUCCESSFUL..

Job: ${JOB_NAME}
Build Number: ${BUILD_NUMBER}

Image pushed:
${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}

Build URL:
${BUILD_URL}
""",
        to: "sudarraja86291@gmail.com"
      )
    }

    failure {
      emailext(
        subject: "FAILED: ${JOB_NAME} #${BUILD_NUMBER}",
        body: """
Build FAILED..

Job: ${JOB_NAME}
Build Number: ${BUILD_NUMBER}

Check logs:
${BUILD_URL}
""",
        to: "sudarraja86291@gmail.com"
      )
    }

    aborted {
      emailext(
        subject: "ABORTED: ${JOB_NAME} #${BUILD_NUMBER}",
        body: """
Build ABORTED..

Reason:
Manual approval was rejected or build was stopped.

Build URL:
${BUILD_URL}
""",
        to: "sudarraja86291@gmail.com"
      )
    }
  }
}
