pipeline {
  agent {
    label 'ssh-agent'
  }

  environment {
    REGISTRY = "buildserver:5000"
    IMAGE_NAME = "user-service"
    IMAGE_TAG = "${BUILD_NUMBER}"
  }


  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Test') {
      steps {
        dir('app') {
          sh 'npm test'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('app') {
          sh """
            docker build -t ${IMAGE_NAME} .
          """
        }
      }
    }
    
    stage('Docker Tag') {
      steps {
        dir('app') {
          sh """
            docker tag -t ${IMAGE_NAME}  ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} 
          """
        }
      }
    }

    stage('Push to Registry') {
      steps {
        sh """
          docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
        """
      }
    }
  }

  post {
    success {
      echo "✅ Image pushed: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
    }
    failure {
      echo "❌ Pipeline failed"
    }
  }
}

