pipeline {
  agent {
    label 'vm-agent'
  }

  environment {
    REGISTRY = "buildserver:5000"
    IMAGE_NAME = "user-service"
    IMAGE_TAG = "${BUILD_NUMBER}"
    SCANNER_HOME = tool 'sonar'
  }

  tools {
    nodejs 'node20'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Test') {
      steps {
        dir('node-microservice/app') {
          sh 'npm test'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('node-microservice/app') {
          withSonarQubeEnv('sonar') {
            sh '''
              $SCANNER_HOME/bin/sonar-scanner \
                -Dsonar.projectKey=user-service \
                -Dsonar.projectName=user-service \
                -Dsonar.sources=.
            '''
          }
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('node-microservice/app') {
          sh "docker build -t ${IMAGE_NAME} ."
        }
      }
    }

    stage('Docker Tag') {
      steps {
        dir('node-microservice/app') {
          sh "docker tag ${IMAGE_NAME} ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
        }
      }
    }

    stage('Push to Registry') {
      steps {
        sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
      }
    }

  }

  post {
    success {
      echo "✅ Image pushed: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
    }
    failure {
      echo "❌ Pipeline failed"
    }
  }
}
